export const styles = {
  block: { display: "block" },
  container: {
    maxWidth: "300px",
    margin: "auto",
    backgroundColor: "#EEE",
    padding: "10px",
    position: "absolute",
    top: "40%",
    left: "50%",
    transform: "translate(-50%, -40%)",
  },
  row: { marginBottom: "5px" },
  label: { float: "left", width: "100px" },
  textbox: { border: "1px solid #CCC", borderRadius: "4px" },
  button: {
    border: "1px solid #CCC",
    borderRadius: "4px",
    paddingTop: "4px",
    paddingBottom: "4px",
    paddingRight: "12px",
    paddingLeft: "12px",
  },
  link: { color: "#88D", textDecoration: "underline" },
  centering: { textAlign: "center" },
};
